name: Lint

on: [push]

jobs:
   eslint:
      runs-on: ubuntu-latest
      steps:
         - name: Checkout
           uses: actions/checkout@v2
         - name: Install PNPM
           run: corepack enable && corepack prepare pnpm@6.32.11 --activate
         - name: Install workspaces
           run: pnpm install
         - name: Run linter
           run: pnpm lint
