name: Type Check

on: [push]

jobs:
   typescript:
      runs-on: ubuntu-latest
      steps:
         - name: Checkout
           uses: actions/checkout@v4
         - name: Install PNPM
           run: corepack enable && corepack prepare pnpm@7.5.2 --activate
         - name: Install workspaces
           run: pnpm install
         - name: Check types
           run: pnpm typecheck
